const $ = id => document.getElementById(id);
const people = {LEDGER:'Finance',ATLAS:'Operations',PULSE:'Marketing',PRISM:'Analytics',NOVA:'People & capacity'};
for(const [name,role] of Object.entries(people)){
 const card=document.createElement('div');card.className='agent';card.id='card-'+name;
 card.innerHTML=`<div class="initial">${name[0]}</div><h3>${name}</h3><p>${role}</p><small id="status-${name}">Ready</small>`;
 $('agents').append(card);
}
let token='', runId=null, seen=0, pollTimer=null, finalText='';
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Session-Token':token},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Request failed');return data;}
async function configure(){try{const c=await api('/api/config');token=c.session_token;$('connection').textContent=c.gemini_ready?'Gemini configured · '+c.model:'Setup needed · Gemini API key';$('telegram').checked=c.telegram_ready;if(!c.gemini_ready){$('setup').open=true;$('notice').textContent='Add your API key in .env and restart to bring the agents live.';}}catch(e){$('notice').textContent=e.message;}}
const presets={budget:'Our launch budget has been cut by 25%. Coordinate all five specialists, resolve conflicts, and give me a revised launch plan. Have ATLAS revise its proposal after LEDGER reviews the cost.',delay:'Our packaging supplier is delayed by 14 days. Coordinate all five specialists to protect the launch. Have LEDGER challenge the recovery costs and ATLAS revise the plan.',launch:'Review our readiness to launch 30,000 beverage units in 84 days with a ₹24 lakh budget. Consult all five specialists. Identify missing evidence, resolve conflicts, and assign next steps.'};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{$('prompt').value=presets[b.dataset.preset];});
function addEvent(e){if(seen===0)$('feed').replaceChildren();seen=e.id;const item=document.createElement('article');item.className='event '+e.kind;const head=document.createElement('div');head.className='event-head';const name=document.createElement('b');name.textContent=e.agent+(e.target?' → '+e.target:'');const kind=document.createElement('span');kind.className='event-kind';kind.textContent=e.kind;const time=document.createElement('time');time.textContent=new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});head.append(name,kind,time);const text=document.createElement('p');text.textContent=e.text;item.append(head,text);$('feed').append(item);$('feed').scrollTop=$('feed').scrollHeight;
 if(e.kind==='working'){$('card-'+e.agent)?.classList.add('active');$('status-'+e.agent).textContent='Working…';}
 if(e.kind==='result'){$('card-'+e.agent)?.classList.remove('active');$('status-'+e.agent).textContent='Reported to JARVIS';}
 if(e.kind==='complete'){finalText=e.text;$('brief').textContent=e.text;$('brief-section').hidden=false;}
}
async function poll(){try{const r=await api('/api/runs/'+runId);for(const e of r.events.filter(e=>e.id>seen))addEvent(e);$('run-status').textContent=r.status.toUpperCase();$('status-JARVIS').textContent=r.status==='running'?'Coordinating…':r.status;$('delivery').textContent=r.telegram?`Telegram: ${r.delivery.sent}/${r.delivery.queued} sent${r.delivery.failed?' · '+r.delivery.failed+' unconfirmed':''}`:'Telegram off';const pending=r.delivery.queued>r.delivery.sent+r.delivery.failed;if(r.status!=='running'){$('start').disabled=false;$('stop').hidden=true;for(const n of Object.keys(people)){if($('card-'+n).classList.contains('active')){$('card-'+n).classList.remove('active');$('status-'+n).textContent=r.status;}}}if(r.status==='running'||pending)pollTimer=setTimeout(poll,1100);}catch(e){$('notice').textContent='Connection interrupted. Retrying; the backend may still be running.';pollTimer=setTimeout(poll,3000);}}
$('start').onclick=async()=>{clearTimeout(pollTimer);$('start').disabled=true;$('notice').textContent='';try{const r=await api('/api/runs',{prompt:$('prompt').value,telegram:$('telegram').checked,delegation_limit:Number($('limit').value)});runId=r.id;seen=0;finalText='';$('brief-section').hidden=true;for(const n of Object.keys(people)){$('card-'+n).classList.remove('active');$('status-'+n).textContent='Ready';}$('stop').hidden=false;$('run-status').textContent='RUNNING';poll();}catch(e){$('notice').textContent=e.message;$('start').disabled=false;}};
$('stop').onclick=async()=>{try{const r=await api('/api/runs/'+runId+'/stop',{});$('notice').textContent=r.message;}catch(e){$('notice').textContent=e.message;}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([finalText],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='aster-'+runId+'-brief.md';a.click();URL.revokeObjectURL(url);};
configure();
